<a href="https://colab.research.google.com/github/rcNibedita/De-Novo-Gen/blob/main/01_Preprocess_ChEMBL_TAK1_Bioactivity_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Mount the Drive (Repeat everytime you create a notebook)
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Relocate to the working directory
!ls "/content/drive/MyDrive/De-Novo"
%cd "/content/drive/MyDrive/De-Novo"
!pwd

01_Preprocess_ChEMBL_TAK1_Bioactivity_Data.ipynb  TAK1_clean_canonical.csv
chembl_raw.csv					  TAK1_clean.csv
/content/drive/MyDrive/De-Novo
/content/drive/MyDrive/De-Novo

In [ ]:
# # File debugging snippet; View the first few lines of the file incase simple pd.read_csv does not load it properly
# with open("chembl_raw.csv", "r", encoding="utf-8") as f:
#     for i in range(15):
#         print(f.readline())

"Molecule ChEMBL ID";"Molecule Name";"Molecule Max Phase";"Molecular Weight";"#RO5 Violations";"AlogP";"Compound Key";"Smiles";"Standard Type";"Standard Relation";"Standard Value";"Standard Units";"pChEMBL Value";"Data Validity Comment";"Comment";"Uo Units";"Ligand Efficiency BEI";"Ligand Efficiency LE";"Ligand Efficiency LLE";"Ligand Efficiency SEI";"Potential Duplicate";"Assay ChEMBL ID";"Assay Description";"Assay Type";"BAO Format ID";"BAO Label";"Assay Organism";"Assay Tissue ChEMBL ID";"Assay Tissue Name";"Assay Cell Type";"Assay Subcellular Fraction";"Assay Parameters";"Assay Variant Accession";"Assay Variant Mutation";"Target ChEMBL ID";"Target Name";"Target Organism";"Target Type";"Document ChEMBL ID";"Source ID";"Source Description";"Document Journal";"Document Year";"Cell ChEMBL ID";"Properties";"Action Type";"Standard Text Value";"Value"

"CHEMBL2407792";"";"None";"446.47";"0";"4.03";"12z";"CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc([N+](=O)[O-])c5)cc34)cn2)CC1";"IC50";"'='";"200.0";"nM";"6.70";"";"";"UO_0000065";"15.00";"0.28";"2.67";"5.02";"0";"CHEMBL2412855";"Inhibition of TAK1 in human HCT116 cells assessed as inhibition of TNF-alpha-stimulated JNK phosphorylation";"B";"BAO_0000219";"cell-based format";"Homo sapiens";"None";"None";"HCT-116";"None";"";"";"";"CHEMBL5776";"Mitogen-activated protein kinase kinase kinase 7";"Homo sapiens";"SINGLE PROTEIN";"CHEMBL2407040";"1";"Scientific Literature";"Bioorg Med Chem Lett";"2013";"CHEMBL3308372";"";"";"";"0.2"

"CHEMBL2407759";"";"None";"459.54";"0";"4.13";"12az";"CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc6nnsc56)cc34)cn2)CC1";"IC50";"'='";"12.0";"nM";"7.92";"";"";"UO_0000065";"17.24";"0.33";"3.79";"6.83";"0";"CHEMBL2412855";"Inhibition of TAK1 in human HCT116 cells assessed as inhibition of TNF-alpha-stimulated JNK phosphorylation";"B";"BAO_0000219";"cell-based format";"Homo sapiens";"None";"None";"HCT-116";"None";"";"";"";"CHEMBL5776";"Mitogen-activated protein kinase kinase kinase 7";"Homo sapiens";"SINGLE PROTEIN";"CHEMBL2407040";"1";"Scientific Literature";"Bioorg Med Chem Lett";"2013";"CHEMBL3308372";"";"";"";"0.012"

"CHEMBL4555884";"";"None";"484.09";"1";"5.19";"1";"COc1cc(Br)cc2[nH]cc(-c3oc(-c4ccc[nH]4)nc3I)c12";"IC50";"'>'";"10000.0";"nM";"";"";"";"UO_0000065";"";"";"";"";"0";"CHEMBL4338194";"Inhibition of TAK1 (unknown origin) by [33P]-ATP filter binding kinase assay";"B";"BAO_0000357";"single protein format";"Homo sapiens";"None";"None";"None";"None";"";"";"";"CHEMBL5776";"Mitogen-activated protein kinase kinase kinase 7";"Homo sapiens";"SINGLE PROTEIN";"CHEMBL4334516";"1";"Scientific Literature";"J Med Chem";"2019";"None";"";"";"";"10.0"

"CHEMBL4446434";"";"None";"358.20";"0";"4.59";"4";"COc1cc(Br)cc2[nH]cc(-c3cnc(-c4ccc[nH]4)o3)c12";"IC50";"'='";"1000.0";"nM";"6.00";"";"";"UO_0000065";"16.75";"0.37";"1.41";"8.98";"0";"CHEMBL4338194";"Inhibition of TAK1 (unknown origin) by [33P]-ATP filter binding kinase assay";"B";"BAO_0000357";"single protein format";"Homo sapiens";"None";"None";"None";"None";"";"";"";"CHEMBL5776";"Mitogen-activated protein kinase kinase kinase 7";"Homo sapiens";"SINGLE PROTEIN";"CHEMBL4334516";"1";"Scientific Literature";"J Med Chem";"2019";"None";"";"";"";"1.0"

"CHEMBL2407763";"";"None";"457.56";"1";"5.34";"12bd";"CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5csc6ccccc56)cc34)cn2)CC1";"IC50";"'='";"440.0";"nM";"6.36";"";"";"UO_0000065";"13.89";"0.26";"1.02";"7.05";"0";"CHEMBL2412855";"Inhibition of TAK1 in human HCT116 cells assessed as inhibition of TNF-alpha-stimulated JNK phosphorylation";"B";"BAO_0000219";"cell-based format";"Homo sapiens";"None";"None";"HCT-116";"None";"";"";"";"CHEMBL5776";"Mitogen-activated protein kinase kinase kinase 7";"Homo sapiens";"SINGLE PROTEIN";"CHEMBL2407040";"1";"Scientific Literature";"Bioorg Med Chem Lett";"2013";"CHEMBL3308372";"";"";"";"0.44"

"CHEMBL3426225";"";"None";"576.63";"1";"4.16";"BDBM50086441";"CCn1nc(C#Cc2cc(C(=O)Nc3ccc(CN4CCN(C)CC4)c(C(F)(F)F)c3)ccc2C)c2c(N)ncnc21";"IC50";"'='";"61.0";"nM";"7.21";"";"756972";"UO_0000065";"12.51";"0.23";"3.05";"6.86";"0";"CHEMBL5733517";"Kinase Inhibition Assays: The aim of this experiment is to detect the inhibitory activity of the compounds of the present invention against in vitro protein kinases using isotope labeling (labeled gamma phosphate groups on ATP). Kinase inhibition profiles were determined using KinaseProfiler services provided by Euro fins, and ATP concentrations used are the Km of corresponding kinases. In this study, we examined Abl (T315I) (h), ALK (h), ARK5 (h), Axl (h), Blk (h), Bmx (h), BTK (h), B-Raf (H), ckit (h), cSRC (h), CDK7, CHK1 (h), c-RAF (h), DDR2 (h), EGFR (h), EphA1 (h), EphA2 (h), EphA8 (h (H), FGF (h), Ft (h), Ft (h), F (h), F (h), Ft (h), Hb (h), ErbB2 (h), FAK (h) (H), JK3 (h), IKKalpha (h), IKKbeta (h), Itk (h), JAK3 (h), JNK11 (h), KDR (h), Lyn (h), MAPK1 (h), MEK1 (h (H), PKA (h), PKB [alpha](h), PKB [beta] (h), PKC [alpha] (h), Ret (H), RIPK2 (h), Src (1-530) (h), TAK1 (h), TBK1 (h), Tec (h) activated, Tie2 (h), TrkA (h), ULK3 (h) Yes (h), PI3 Kinase a (h) and other kinase in vitro inhibitory activity. The kinase inhibitory activity of the test compound is expressed as IC50 (half inhibitory concentration) or the inhibitory rate of the test compound at a concentration of 10 ??M for kinase activity. IC50 values can be obtained by calculating the inhibition rate of the kinase activity by the test compound at a series of different concentrations. The assay was as follows: In a reaction tube, the buffer (8 mM MOPS, pH 7.0, 0.2 mM EDTA, 10 mM MnCl2), the kinase to be tested (5-10 mU), the substrate to be tested kinase, 10 mM acetic acid Magnesium and gamma 33P-ATP solutions, as well as different concentrations of the test compound. MgATP was then added to the reaction to initiate the enzymatic reaction and incubated at room temperature for 40 minutes. The reaction was finally quenched with 5 ul of 3% phosphate buffer and 10 uL of the reaction solution was titrated onto a filtermat A membrane, washed three times with 75 mM phosphate solution for 5 minutes each, and washed again with methanol. Finally, the filtermat A film is dried and scintigraphized, and the size of the scintillation count reflects the degree to which the substrate is phosphorylated, thereby demonstrating that the kinase activity is inhibited. Among them, the percentage of the remaining active protein=the active protein of the experimental group the active protein of the control group 100%.";"B";"BAO_0000019";"assay format";"Homo sapiens";"None";"None";"None";"None";"";"";"";"CHEMBL5776";"Mitogen-activated protein kinase kinase kinase 7";"Homo sapiens";"SINGLE PROTEIN";"CHEMBL5726853";"37";"BindingDB Patent Bioactivity Data";"";"2019";"None";"";"";"";"61.0"

"CHEMBL4787515";"";"None";"533.56";"1";"4.65";"BDBM378887";"Cc1ccc(NC(=O)c2cccc(C(F)(F)F)c2)cc1C#Cc1nn(C2CCN(C)CC2)c2ncnc(N)c12";"IC50";"'='";"203.0";"nM";"6.69";"";"756973";"UO_0000065";"12.54";"0.23";"2.04";"6.56";"0";"CHEMBL5733517";"Kinase Inhibition Assays: The aim of this experiment is to detect the inhibitory activity of the compounds of the present invention against in vitro protein kinases using isotope labeling (labeled gamma phosphate groups on ATP). Kinase inhibition profiles were determined using KinaseProfiler services provided by Euro fins, and ATP concentrations used are the Km of corresponding kinases. In this study, we examined Abl (T315I) (h), ALK (h), ARK5 (h), Axl (h), Blk (h), Bmx (h), BTK (h), B-Raf (H), ckit (h), cSRC (h), CDK7, CHK1 (h), c-RAF (h), DDR2 (h), EGFR (h), EphA1 (h), EphA2 (h), EphA8 (h (H), FGF (h), Ft (h), Ft (h), F (h), F (h), Ft (h), Hb (h), ErbB2 (h), FAK (h) (H), JK3 (h), IKKalpha (h), IKKbeta (h), Itk (h), JAK3 (h), JNK11 (h), KDR (h), Lyn (h), MAPK1 (h), MEK1 (h (H), PKA (h), PKB [alpha](h), PKB [beta] (h), PKC [alpha] (h), Ret (H), RIPK2 (h), Src (1-530) (h), TAK1 (h), TBK1 (h), Tec (h) activated, Tie2 (h), TrkA (h), ULK3 (h) Yes (h), PI3 Kinase a (h) and other kinase in vitro inhibitory activity. The kinase inhibitory activity of the test compound is expressed as IC50 (half inhibitory concentration) or the inhibitory rate of the test compound at a concentration of 10 ??M for kinase activity. IC50 values can be obtained by calculating the inhibition rate of the kinase activity by the test compound at a series of different concentrations. The assay was as follows: In a reaction tube, the buffer (8 mM MOPS, pH 7.0, 0.2 mM EDTA, 10 mM MnCl2), the kinase to be tested (5-10 mU), the substrate to be tested kinase, 10 mM acetic acid Magnesium and gamma 33P-ATP solutions, as well as different concentrations of the test compound. MgATP was then added to the reaction to initiate the enzymatic reaction and incubated at room temperature for 40 minutes. The reaction was finally quenched with 5 ul of 3% phosphate buffer and 10 uL of the reaction solution was titrated onto a filtermat A membrane, washed three times with 75 mM phosphate solution for 5 minutes each, and washed again with methanol. Finally, the filtermat A film is dried and scintigraphized, and the size of the scintillation count reflects the degree to which the substrate is phosphorylated, thereby demonstrating that the kinase activity is inhibited. Among them, the percentage of the remaining active protein=the active protein of the experimental group the active protein of the control group 100%.";"B";"BAO_0000019";"assay format";"Homo sapiens";"None";"None";"None";"None";"";"";"";"CHEMBL5776";"Mitogen-activated protein kinase kinase kinase 7";"Homo sapiens";"SINGLE PROTEIN";"CHEMBL5726853";"37";"BindingDB Patent Bioactivity Data";"";"2019";"None";"";"";"";"203.0"

"CHEMBL2407770";"";"None";"444.50";"0";"3.22";"12ak";"CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc(C(N)=O)c5)cc34)cn2)CC1";"IC50";"'='";"3100.0";"nM";"5.51";"";"";"UO_0000065";"12.39";"0.23";"2.29";"4.13";"0";"CHEMBL2412855";"Inhibition of TAK1 in human HCT116 cells assessed as inhibition of TNF-alpha-stimulated JNK phosphorylation";"B";"BAO_0000219";"cell-based format";"Homo sapiens";"None";"None";"HCT-116";"None";"";"";"";"CHEMBL5776";"Mitogen-activated protein kinase kinase kinase 7";"Homo sapiens";"SINGLE PROTEIN";"CHEMBL2407040";"1";"Scientific Literature";"Bioorg Med Chem Lett";"2013";"CHEMBL3308372";"";"";"";"3.1"

"CHEMBL2407772";"";"None";"431.50";"0";"3.62";"12am";"CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc(CO)c5)cc34)cn2)CC1";"IC50";"'='";"470.0";"nM";"6.33";"";"";"UO_0000065";"14.66";"0.27";"2.71";"5.73";"0";"CHEMBL2412855";"Inhibition of TAK1 in human HCT116 cells assessed as inhibition of TNF-alpha-stimulated JNK phosphorylation";"B";"BAO_0000219";"cell-based format";"Homo sapiens";"None";"None";"HCT-116";"None";"";"";"";"CHEMBL5776";"Mitogen-activated protein kinase kinase kinase 7";"Homo sapiens";"SINGLE PROTEIN";"CHEMBL2407040";"1";"Scientific Literature";"Bioorg Med Chem Lett";"2013";"CHEMBL3308372";"";"";"";"0.47"

"CHEMBL2407767";"";"None";"426.48";"0";"4.00";"12ah";"CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc(C#N)c5)cc34)cn2)CC1";"IC50";"'='";"370.0";"nM";"6.43";"";"";"UO_0000065";"15.08";"0.27";"2.43";"5.64";"0";"CHEMBL2412855";"Inhibition of TAK1 in human HCT116 cells assessed as inhibition of TNF-alpha-stimulated JNK phosphorylation";"B";"BAO_0000219";"cell-based format";"Homo sapiens";"None";"None";"HCT-116";"None";"";"";"";"CHEMBL5776";"Mitogen-activated protein kinase kinase kinase 7";"Homo sapiens";"SINGLE PROTEIN";"CHEMBL2407040";"1";"Scientific Literature";"Bioorg Med Chem Lett";"2013";"CHEMBL3308372";"";"";"";"0.37"

"CHEMBL3884616";"";"None";"451.91";"0";"4.55";"20";"C=CC(=O)Oc1ccccc1Nc1nc(Nc2cccc(N3CCOCC3)c2)ncc1Cl";"IC50";"'='";"3.2";"nM";"8.49";"";"";"UO_0000065";"18.80";"0.36";"3.94";"9.59";"1";"CHEMBL4118523";"Inhibition of TAK1 (unknown origin) by LanthaScreen assay";"B";"BAO_0000357";"single protein format";"Homo sapiens";"None";"None";"None";"None";"";"";"";"CHEMBL5776";"Mitogen-activated protein kinase kinase kinase 7";"Homo sapiens";"SINGLE PROTEIN";"CHEMBL4118021";"1";"Scientific Literature";"Bioorg Med Chem";"2017";"None";"";"";"";"3.2"

"CHEMBL3884143";"";"None";"370.80";"0";"3.52";"22";"C=CC(=O)Nc1ccccc1Oc1nc(Nc2cnn(C)c2)ncc1Cl";"IC50";"'='";"7.3";"nM";"8.14";"";"";"UO_0000065";"21.94";"0.43";"4.62";"8.66";"1";"CHEMBL4118523";"Inhibition of TAK1 (unknown origin) by LanthaScreen assay";"B";"BAO_0000357";"single protein format";"Homo sapiens";"None";"None";"None";"None";"";"";"";"CHEMBL5776";"Mitogen-activated protein kinase kinase kinase 7";"Homo sapiens";"SINGLE PROTEIN";"CHEMBL4118021";"1";"Scientific Literature";"Bioorg Med Chem";"2017";"None";"";"";"";"7.3"

"CHEMBL2408735";"";"None";"372.41";"0";"3.96";"6r";"Cn1cc(-c2cnc(N)c3oc(-c4csc5cnccc45)cc23)c(C#N)n1";"IC50";"'>'";"10000.0";"nM";"";"";"";"UO_0000065";"";"";"";"";"0";"CHEMBL2410822";"Inhibition of TAK1 in human HCT116 cells assessed as inhibition of TNF-alpha-stimulated JNK phosphorylation";"B";"BAO_0000219";"cell-based format";"Homo sapiens";"None";"None";"HCT-116";"None";"";"";"";"CHEMBL5776";"Mitogen-activated protein kinase kinase kinase 7";"Homo sapiens";"SINGLE PROTEIN";"CHEMBL2407065";"1";"Scientific Literature";"Bioorg Med Chem Lett";"2013";"CHEMBL3308372";"";"";"";"10.0"

"CHEMBL3884914";"";"None";"470.58";"0";"4.77";"15";"C=CC(=O)Nc1ccccc1Oc1nc(Nc2ccc(N3CCN(C)CC3)cc2)ncc1C1CC1";"IC50";"'='";"57.0";"nM";"7.24";"";"";"UO_0000065";"15.39";"0.28";"2.47";"8.77";"1";"CHEMBL4118523";"Inhibition of TAK1 (unknown origin) by LanthaScreen assay";"B";"BAO_0000357";"single protein format";"Homo sapiens";"None";"None";"None";"None";"";"";"";"CHEMBL5776";"Mitogen-activated protein kinase kinase kinase 7";"Homo sapiens";"SINGLE PROTEIN";"CHEMBL4118021";"1";"Scientific Literature";"Bioorg Med Chem";"2017";"None";"";"";"";"57.0"

In [ ]:
# ============================================================
# Install Required Packages
# ============================================================
!pip -q install rdkit

In [ ]:
# ============================================================
# Import Required Libraries
# ============================================================

import pandas as pd
import numpy as np

from rdkit import Chem

print("Libraries imported successfully.")

Libraries imported successfully.

In [ ]:
# ============================================================
# Load the ChEMBL Bioactivity Dataset
# ============================================================

# If using Google Drive
# df = pd.read_csv("/content/drive/MyDrive/De-Novo/chembl_raw.csv")

# If uploaded directly into Colab
df = pd.read_csv("chembl_raw.csv",
                 sep=";",
                 quotechar='"')

print("Dataset loaded successfully.")
print("Number of records:", len(df))

Dataset loaded successfully.
Number of records: 343

In [ ]:
# ============================================================
# Inspect Dataset
# ============================================================

print(df.head())

print("\nColumns available:\n")
print(df.columns.tolist())

  Molecule ChEMBL ID Molecule Name  Molecule Max Phase  Molecular Weight  \
0      CHEMBL2407792           NaN                 NaN            446.47
1      CHEMBL2407759           NaN                 NaN            459.54
2      CHEMBL4555884           NaN                 NaN            484.09
3      CHEMBL4446434           NaN                 NaN            358.20
4      CHEMBL2407763           NaN                 NaN            457.56

   #RO5 Violations  AlogP Compound Key  \
0                0   4.03          12z
1                0   4.13         12az
2                1   5.19            1
3                0   4.59            4
4                1   5.34         12bd

                                              Smiles Standard Type  \
0  CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc([N+](=O...          IC50
1  CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc6nnsc56)...          IC50
2     COc1cc(Br)cc2[nH]cc(-c3oc(-c4ccc[nH]4)nc3I)c12          IC50
3      COc1cc(Br)cc2[nH]cc(-c3cnc(-c4ccc[nH]4)o3)c12          IC50
4  CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5csc6ccccc56)...          IC50

  Standard Relation  ...  Document ChEMBL ID Source ID     Source Description  \
0               '='  ...       CHEMBL2407040         1  Scientific Literature
1               '='  ...       CHEMBL2407040         1  Scientific Literature
2               '>'  ...       CHEMBL4334516         1  Scientific Literature
3               '='  ...       CHEMBL4334516         1  Scientific Literature
4               '='  ...       CHEMBL2407040         1  Scientific Literature

       Document Journal Document Year Cell ChEMBL ID  Properties  Action Type  \
0  Bioorg Med Chem Lett          2013  CHEMBL3308372         NaN          NaN
1  Bioorg Med Chem Lett          2013  CHEMBL3308372         NaN          NaN
2            J Med Chem          2019            NaN         NaN          NaN
3            J Med Chem          2019            NaN         NaN          NaN
4  Bioorg Med Chem Lett          2013  CHEMBL3308372         NaN          NaN

   Standard Text Value   Value
0                  NaN   0.200
1                  NaN   0.012
2                  NaN  10.000
3                  NaN   1.000
4                  NaN   0.440

[5 rows x 48 columns]

Columns available:

['Molecule ChEMBL ID', 'Molecule Name', 'Molecule Max Phase', 'Molecular Weight', '#RO5 Violations', 'AlogP', 'Compound Key', 'Smiles', 'Standard Type', 'Standard Relation', 'Standard Value', 'Standard Units', 'pChEMBL Value', 'Data Validity Comment', 'Comment', 'Uo Units', 'Ligand Efficiency BEI', 'Ligand Efficiency LE', 'Ligand Efficiency LLE', 'Ligand Efficiency SEI', 'Potential Duplicate', 'Assay ChEMBL ID', 'Assay Description', 'Assay Type', 'BAO Format ID', 'BAO Label', 'Assay Organism', 'Assay Tissue ChEMBL ID', 'Assay Tissue Name', 'Assay Cell Type', 'Assay Subcellular Fraction', 'Assay Parameters', 'Assay Variant Accession', 'Assay Variant Mutation', 'Target ChEMBL ID', 'Target Name', 'Target Organism', 'Target Type', 'Document ChEMBL ID', 'Source ID', 'Source Description', 'Document Journal', 'Document Year', 'Cell ChEMBL ID', 'Properties', 'Action Type', 'Standard Text Value', 'Value']

In [ ]:
# ============================================================
# Inspect Bioactivity Columns
# ============================================================

bioactivity = df[
    [
        "Molecule ChEMBL ID",
        "Smiles",
        "Standard Type",
        "Standard Relation",
        "Standard Value",
        "Standard Units",
        "pChEMBL Value"
    ]
]

bioactivity.head(20)

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Relation,Standard Value,Standard Units,pChEMBL Value
0,CHEMBL2407792,CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc([N+](=O...,IC50,'=',200.0,nM,6.70
1,CHEMBL2407759,CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc6nnsc56)...,IC50,'=',12.0,nM,7.92
2,CHEMBL4555884,COc1cc(Br)cc2[nH]cc(-c3oc(-c4ccc[nH]4)nc3I)c12,IC50,'>',10000.0,nM,NaN
3,CHEMBL4446434,COc1cc(Br)cc2[nH]cc(-c3cnc(-c4ccc[nH]4)o3)c12,IC50,'=',1000.0,nM,6.00
4,CHEMBL2407763,CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5csc6ccccc56)...,IC50,'=',440.0,nM,6.36
5,CHEMBL3426225,CCn1nc(C#Cc2cc(C(=O)Nc3ccc(CN4CCN(C)CC4)c(C(F)...,IC50,'=',61.0,nM,7.21
6,CHEMBL4787515,Cc1ccc(NC(=O)c2cccc(C(F)(F)F)c2)cc1C#Cc1nn(C2C...,IC50,'=',203.0,nM,6.69
7,CHEMBL2407770,CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc(C(N)=O)...,IC50,'=',3100.0,nM,5.51
8,CHEMBL2407772,CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc(CO)c5)c...,IC50,'=',470.0,nM,6.33
9,CHEMBL2407767,CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc(C#N)c5)...,IC50,'=',370.0,nM,6.43
10,CHEMBL3884616,C=CC(=O)Oc1ccccc1Nc1nc(Nc2cccc(N3CCOCC3)c2)ncc1Cl,IC50,'=',3.2,nM,8.49
11,CHEMBL3884143,C=CC(=O)Nc1ccccc1Oc1nc(Nc2cnn(C)c2)ncc1Cl,IC50,'=',7.3,nM,8.14
12,CHEMBL2408735,Cn1cc(-c2cnc(N)c3oc(-c4csc5cnccc45)cc23)c(C#N)n1,IC50,'>',10000.0,nM,NaN
13,CHEMBL3884914,C=CC(=O)Nc1ccccc1Oc1nc(Nc2ccc(N3CCN(C)CC3)cc2)...,IC50,'=',57.0,nM,7.24
14,CHEMBL5705831,CCN1CCN(Cc2ccc(NC(=O)c3cccc(Oc4ccnc5[nH]ccc45)...,IC50,'=',119.0,nM,6.92
15,CHEMBL5705839,CCN1CCN(Cc2ccc(NC(=O)c3ccc(OC)c(Oc4ncnc5[nH]cc...,IC50,'=',292.0,nM,6.54
16,CHEMBL5876900,COc1cc(O)c2c(c1Br)/C=C\C[C@H](O)[C@H](O)C(=O)/...,IC50,'=',360.0,nM,6.44
17,CHEMBL3629246,COc1c(Br)c(O)c2c(c1Br)/C=C/C[C@H](O)[C@H](O)C(...,IC50,'=',8900.0,nM,5.05
18,CHEMBL2407790,CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc(S(N)(=O...,IC50,NaN,NaN,NaN,NaN
19,CHEMBL2407789,CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc(S(C)(=O...,IC50,'=',1100.0,nM,5.96

In [ ]:
# ============================================================
# Inspect Missing Bioactivity Values
# ============================================================
print(df[df["Standard Units"].isna()][[
    "Molecule ChEMBL ID",
    "Standard Type",
    "Standard Relation",
    "Standard Value",
    "Standard Units"
]])

print()

print("Missing Standard Units")
print(df["Standard Units"].isna().sum())

print("Missing SMILES")
print(df["Smiles"].isna().sum())

    Molecule ChEMBL ID Standard Type Standard Relation  Standard Value  \
18       CHEMBL2407790          IC50               NaN             NaN
36       CHEMBL4460150          IC50               NaN             NaN
44       CHEMBL2407754          IC50               NaN             NaN
45       CHEMBL2407776          IC50               NaN             NaN
59       CHEMBL2407782          IC50               NaN             NaN
60       CHEMBL2407780          IC50               NaN             NaN
154      CHEMBL2407764          IC50               NaN             NaN
177      CHEMBL4569421          IC50               NaN             NaN
178      CHEMBL4462060          IC50               NaN             NaN

    Standard Units
18             NaN
36             NaN
44             NaN
45             NaN
59             NaN
60             NaN
154            NaN
177            NaN
178            NaN

Missing Standard Units
9
Missing SMILES
0

In [ ]:
# ============================================================
# Inspect Bioactivity Type, Units & Relations
# ============================================================

# Confirm if all instances are IC50 type
print(df["Standard Type"].value_counts())

# Count and display different instances of Standard Relation
print(df["Standard Relation"].value_counts(dropna=False))

# Display different instances of Standard Units
print("Standard Units:", df["Standard Units"].unique())

Standard Type
IC50    343
Name: count, dtype: int64
Standard Relation
'='    299
'>'     33
NaN      9
'<'      1
'~'      1
Name: count, dtype: int64
Standard Units: ['nM' nan "10'-4nM"]

In [ ]:
# ===================================================================
# Inspect bioactivity-related columns with specific erroneous values
# ===================================================================
# df[df["Standard Units"] == "10'-4nM"][
#     [
#         "Molecule ChEMBL ID",
#         "Standard Type",
#         "Standard Relation",
#         "Standard Value",
#         "Standard Units",
#         "Assay Description",
#         "Document ChEMBL ID"
#     ]
# ]

In [ ]:
# ============================================================
# Keep Potent Compounds (IC50 ≤ 1000 nM)
# ============================================================
df_active = df[
    (df["Standard Type"] == "IC50") &
    (df["Standard Units"] == "nM") &
    (df["Standard Value"] <= 1000) &
    (df["Standard Relation"].isin(["'='", "'<'"]))
].copy()
print(f"Number of compounds retained: {len(df_active)}")
df_active.head()

Number of compounds retained: 226

,Molecule ChEMBL ID,Molecule Name,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Compound Key,Smiles,Standard Type,Standard Relation,...,Document ChEMBL ID,Source ID,Source Description,Document Journal,Document Year,Cell ChEMBL ID,Properties,Action Type,Standard Text Value,Value
0,CHEMBL2407792,NaN,NaN,446.47,0,4.03,12z,CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc([N+](=O...,IC50,'=',...,CHEMBL2407040,1,Scientific Literature,Bioorg Med Chem Lett,2013,CHEMBL3308372,NaN,NaN,NaN,0.200
1,CHEMBL2407759,NaN,NaN,459.54,0,4.13,12az,CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5cccc6nnsc56)...,IC50,'=',...,CHEMBL2407040,1,Scientific Literature,Bioorg Med Chem Lett,2013,CHEMBL3308372,NaN,NaN,NaN,0.012
3,CHEMBL4446434,NaN,NaN,358.20,0,4.59,4,COc1cc(Br)cc2[nH]cc(-c3cnc(-c4ccc[nH]4)o3)c12,IC50,'=',...,CHEMBL4334516,1,Scientific Literature,J Med Chem,2019,NaN,NaN,NaN,NaN,1.000
4,CHEMBL2407763,NaN,NaN,457.56,1,5.34,12bd,CC(=O)N1CCC(n2cc(-c3cnc(N)c4oc(-c5csc6ccccc56)...,IC50,'=',...,CHEMBL2407040,1,Scientific Literature,Bioorg Med Chem Lett,2013,CHEMBL3308372,NaN,NaN,NaN,0.440
5,CHEMBL3426225,NaN,NaN,576.63,1,4.16,BDBM50086441,CCn1nc(C#Cc2cc(C(=O)Nc3ccc(CN4CCN(C)CC4)c(C(F)...,IC50,'=',...,CHEMBL5726853,37,BindingDB Patent Bioactivity Data,NaN,2019,NaN,NaN,NaN,NaN,61.000

In [ ]:
# ============================================================
# Remove Molecules Without SMILES
# ============================================================
before = len(df_active)

df_active = df_active.dropna(
    subset=["Smiles"]
)

print("Removed null values:", before-len(df_active))
print("Remaining:", len(df_active))

# ============================================================
# Remove Duplicate SMILES
# ============================================================

before = len(df_active)

df_active = df_active.drop_duplicates(
    subset=["Smiles"]
)

print("Duplicates removed:", before-len(df_active))
print("Remaining:", len(df_active))

# ============================================================
# Export the Cleaned File
# ============================================================
df_active.to_csv("TAK1_clean.csv",index=False)

Removed null values: 0
Remaining: 226
Duplicates removed: 48
Remaining: 178

In [ ]:
# ============================================================
# Canonicalize SMILES
# ============================================================
def canonicalize(smiles):
    if pd.isna(smiles):
        return None
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    return Chem.MolToSmiles(mol, canonical=True)

df_active["Canonical_SMILES"] = df_active["Smiles"].apply(canonicalize)
print("Canonicalization completed.")

Canonicalization completed.

In [ ]:
# ============================================================
# Remove Invalid Molecules
# ============================================================
before = len(df_active)

df_active = df_active.dropna(
    subset=["Canonical_SMILES"]
)

print("Invalid molecules removed:", before-len(df_active))
print("Remaining:", len(df_active))

# ============================================================
# Remove Duplicate Canonical Molecules
# ============================================================

before = len(df_active)

df_active = df_active.drop_duplicates(
    subset=["Canonical_SMILES"]
)

print("Canonical duplicates removed:",
      before-len(df_active))

print("Final dataset size:",
      len(df_active))

Invalid molecules removed: 0
Remaining: 178
Canonical duplicates removed: 0
Final dataset size: 178

In [ ]:
# ============================================================
# Inspect Final Dataset
# ============================================================

df_active.head()

# ============================================================
# Export Clean Dataset
# ============================================================

df_active.to_csv(
    "TAK1_clean_canonical.csv",
    index=False
)

print("TAK1_clean_canonical.csv saved successfully.")

TAK1_clean_canonical.csv saved successfully.

In [ ]:
# ============================================================
# Dataset Summary
# ============================================================

print("="*50)

print("FINAL DATASET SUMMARY")

print("="*50)

print("Total compounds:",
      len(df_active))

print()

print("Columns:")

print(df_active.columns.tolist())

==================================================
FINAL DATASET SUMMARY
==================================================
Total compounds: 178

Columns:
['Molecule ChEMBL ID', 'Molecule Name', 'Molecule Max Phase', 'Molecular Weight', '#RO5 Violations', 'AlogP', 'Compound Key', 'Smiles', 'Standard Type', 'Standard Relation', 'Standard Value', 'Standard Units', 'pChEMBL Value', 'Data Validity Comment', 'Comment', 'Uo Units', 'Ligand Efficiency BEI', 'Ligand Efficiency LE', 'Ligand Efficiency LLE', 'Ligand Efficiency SEI', 'Potential Duplicate', 'Assay ChEMBL ID', 'Assay Description', 'Assay Type', 'BAO Format ID', 'BAO Label', 'Assay Organism', 'Assay Tissue ChEMBL ID', 'Assay Tissue Name', 'Assay Cell Type', 'Assay Subcellular Fraction', 'Assay Parameters', 'Assay Variant Accession', 'Assay Variant Mutation', 'Target ChEMBL ID', 'Target Name', 'Target Organism', 'Target Type', 'Document ChEMBL ID', 'Source ID', 'Source Description', 'Document Journal', 'Document Year', 'Cell ChEMBL ID', 'Properties', 'Action Type', 'Standard Text Value', 'Value', 'Canonical_SMILES']